CREATE SCHEMA IF NOT EXISTS PRACTICA_FINAL_DAW.WAREHOUSE;
USE SCHEMA PRACTICA_FINAL_DAW.WAREHOUSE;

-- DIM_TIENDA: Incluye país, zona horaria y moneda local
CREATE OR REPLACE TABLE DIM_TIENDA AS
SELECT 
    t.ID_TIENDA,
    n.N_NAME AS PAIS_TIENDA,
    n.N_TIMEZONE AS ZONA_HORARIA_TIENDA,
    c.MONEDA AS MONEDA_TIENDA,
    c.TIPO_CAMBIO_USD AS TIPO_CAMBIO_TIENDA
FROM PRACTICA_FINAL_DAW.STAGING.STG_TIENDA t
LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_NATION n ON t.N_NATIONKEY = n.N_NATIONKEY
LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_CAMBIO c ON n.N_NATIONKEY = c.N_NATIONKEY;

-- DIM_CLIENTE: Incluye región, país, zona horaria y moneda local
CREATE OR REPLACE TABLE DIM_CLIENTE AS
SELECT 
    cust.C_CUSTKEY AS ID_CLIENTE,
    cust.C_NAME AS NOMBRE_CLIENTE,
    n.N_NAME AS PAIS_CLIENTE,
    r.R_NAME AS REGION_CLIENTE,
    n.N_TIMEZONE AS ZONA_HORARIA_CLIENTE,
    c.MONEDA AS MONEDA_CLIENTE,
    c.TIPO_CAMBIO_USD AS TIPO_CAMBIO_CLIENTE
FROM PRACTICA_FINAL_DAW.STAGING.STG_CUSTOMER cust
LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_NATION n ON cust.C_NATIONKEY = n.N_NATIONKEY
LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_CAMBIO c ON n.N_NATIONKEY = c.N_NATIONKEY;

-- DIM_PROMOCION
CREATE OR REPLACE TABLE DIM_PROMOCION AS
SELECT 
    ID_PROMOCION,
    NOMBRE_PROMO,
    FECHA_INICIO,
    FECHA_FIN,
    N_NATIONKEY AS ID_PAIS_PROMO
FROM PRACTICA_FINAL_DAW.STAGING.STG_PROMOCION;

-- DIM_ARTICULO
CREATE OR REPLACE TABLE DIM_ARTICULO AS
SELECT 
    P_PARTKEY AS ID_ARTICULO,
    P_NAME AS NOMBRE_ARTICULO,
    P_TYPE AS TIPO_ARTICULO
FROM PRACTICA_FINAL_DAW.STAGING.STG_PART;

CREATE OR REPLACE TABLE FACT_VENTAS AS
SELECT 
    base.ID_PEDIDO,
    base.ID_LINEA,
    base.ID_ARTICULO,
    base.ID_TIENDA,
    base.ID_CLIENTE,
    base.ID_PROMOCION,
    base.TIPO_OPERACION,
    base.UNIDADES,
    base.IMPORTE_USD,
    -- Cálculo de moneda local
    ROUND(base.IMPORTE_USD * dt.TIPO_CAMBIO_TIENDA, 2) AS IMPORTE_MONEDA_TIENDA,
    ROUND(base.IMPORTE_USD * dc.TIPO_CAMBIO_CLIENTE, 2) AS IMPORTE_MONEDA_CLIENTE,
    base.FECHA_HORA_PEDIDO_UTC,
    -- Conversión a horas locales
    CONVERT_TIMEZONE('UTC', dt.ZONA_HORARIA_TIENDA, base.FECHA_HORA_PEDIDO_UTC) AS FECHA_HORA_LOCAL_TIENDA,
    CONVERT_TIMEZONE('UTC', dc.ZONA_HORARIA_CLIENTE, base.FECHA_HORA_PEDIDO_UTC) AS FECHA_HORA_LOCAL_CLIENTE,
    -- Cálculo del Plazo de Entrega (0, 1 o 2)
    CASE 
        WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 0 THEN 1 -- En plazo
        WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 10 THEN 2 -- Entrega tardía
        ELSE 0 -- Fuera de plazo
    END AS ID_PLAZO_ENTREGA
FROM (
    -- Subconsulta principal para preparar los datos brutos antes de cruzar con las dimensiones finales
    SELECT 
        l.L_ORDERKEY AS ID_PEDIDO,
        l.L_LINENUMBER AS ID_LINEA,
        l.L_PARTKEY AS ID_ARTICULO,
        o.O_STOREKEY AS ID_TIENDA,
        o.O_CUSTKEY AS ID_CLIENTE,
        prom.ID_PROMOCION,
        -- Determinamos si es Venta o Devolución (R = Return)
        CASE 
            WHEN l.L_RETURNFLAG = 'R' THEN 'Devolución'
            ELSE 'Venta'
        END AS TIPO_OPERACION,
        l.L_QUANTITY AS UNIDADES,
        l.L_EXTENDEDPRICE AS IMPORTE_USD,
        o.O_ORDERDATETIME AS FECHA_HORA_PEDIDO_UTC,
        l.L_COMMITDATE AS FECHA_ESTIMADA,
        l.L_RECEIPTDATE AS FECHA_ENTREGA
    FROM PRACTICA_FINAL_DAW.STAGING.STG_LINEITEM l
    INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_ORDERS o ON l.L_ORDERKEY = o.O_ORDERKEY
    INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_TIENDA t ON o.O_STOREKEY = t.ID_TIENDA
    -- Cruce para asignar la promoción según la fecha del pedido y el país
    LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_PROMOCION prom 
        ON o.O_ORDERDATE >= prom.FECHA_INICIO 
        AND o.O_ORDERDATE <= prom.FECHA_FIN
        AND (prom.N_NATIONKEY IS NULL OR prom.N_NATIONKEY = t.N_NATIONKEY)
) AS base
-- Cruzamos la subconsulta con nuestras nuevas dimensiones para obtener los tipos de cambio y zonas horarias
LEFT JOIN DIM_TIENDA dt ON base.ID_TIENDA = dt.ID_TIENDA
LEFT JOIN DIM_CLIENTE dc ON base.ID_CLIENTE = dc.ID_CLIENTE;