-- 1. Creamos la base de datos para el proyecto y la seleccionamos
CREATE DATABASE IF NOT EXISTS PRACTICA_FINAL_DAW;
USE DATABASE PRACTICA_FINAL_DAW;

-- 2. Creamos la capa RAW (nuestra zona de aterrizaje)
CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;

-- 3. Clonamos las tablas del dataset original TPC-H (SF1)
-- Utilizamos CTAS (Create Table As Select) para copiar estructura y datos a la vez
CREATE OR REPLACE TABLE RAW_ORDERS AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

CREATE OR REPLACE TABLE RAW_LINEITEM AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

CREATE OR REPLACE TABLE RAW_PART AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

CREATE OR REPLACE TABLE RAW_CUSTOMER AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE OR REPLACE TABLE RAW_NATION AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

CREATE OR REPLACE TABLE RAW_REGION AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;