USE DATABASE PRACTICA_FINAL_DAW;

-- 1. Forzamos la creación del Stream explícitamente dentro de RAW
CREATE OR REPLACE STREAM PRACTICA_FINAL_DAW.RAW.STREAM_NUEVAS_VENTAS 
ON TABLE PRACTICA_FINAL_DAW.RAW.RAW_LINEITEM;

-- 2. Forzamos la creación de la Task explícitamente dentro de WAREHOUSE
CREATE OR REPLACE TASK PRACTICA_FINAL_DAW.WAREHOUSE.TASK_ACTUALIZAR_FACT_VENTAS
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('PRACTICA_FINAL_DAW.RAW.STREAM_NUEVAS_VENTAS')
AS
  INSERT INTO PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS
  SELECT 
      base.ID_PEDIDO, base.ID_LINEA, base.ID_ARTICULO, base.ID_TIENDA, 
      base.ID_CLIENTE, base.ID_PROMOCION, base.TIPO_OPERACION, base.UNIDADES, 
      base.IMPORTE_USD,
      ROUND(base.IMPORTE_USD * dt.TIPO_CAMBIO_TIENDA, 2),
      ROUND(base.IMPORTE_USD * dc.TIPO_CAMBIO_CLIENTE, 2),
      base.FECHA_HORA_PEDIDO_UTC,
      CONVERT_TIMEZONE('UTC', dt.ZONA_HORARIA_TIENDA, base.FECHA_HORA_PEDIDO_UTC),
      CONVERT_TIMEZONE('UTC', dc.ZONA_HORARIA_CLIENTE, base.FECHA_HORA_PEDIDO_UTC),
      CASE 
          WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 0 THEN 1
          WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 10 THEN 2
          ELSE 0
      END
  FROM (
      SELECT 
          s.L_ORDERKEY AS ID_PEDIDO, s.L_LINENUMBER AS ID_LINEA, s.L_PARTKEY AS ID_ARTICULO,
          o.O_STOREKEY AS ID_TIENDA, o.O_CUSTKEY AS ID_CLIENTE, prom.ID_PROMOCION,
          CASE WHEN s.L_RETURNFLAG = 'R' THEN 'Devolución' ELSE 'Venta' END AS TIPO_OPERACION,
          s.L_QUANTITY AS UNIDADES, s.L_EXTENDEDPRICE AS IMPORTE_USD,
          o.O_ORDERDATETIME AS FECHA_HORA_PEDIDO_UTC, s.L_COMMITDATE AS FECHA_ESTIMADA, s.L_RECEIPTDATE AS FECHA_ENTREGA
      FROM PRACTICA_FINAL_DAW.RAW.STREAM_NUEVAS_VENTAS s
      INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_ORDERS o ON s.L_ORDERKEY = o.O_ORDERKEY
      INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_TIENDA t ON o.O_STOREKEY = t.ID_TIENDA
      LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_PROMOCION prom 
          ON o.O_ORDERDATE >= prom.FECHA_INICIO 
          AND o.O_ORDERDATE <= prom.FECHA_FIN
          AND (prom.N_NATIONKEY IS NULL OR prom.N_NATIONKEY = t.N_NATIONKEY)
      WHERE s.METADATA$ACTION = 'INSERT' AND s.METADATA$ISUPDATE = FALSE
  ) AS base
  LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_TIENDA dt ON base.ID_TIENDA = dt.ID_TIENDA
  LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON base.ID_CLIENTE = dc.ID_CLIENTE;

-- 3. Arrancar la Task
ALTER TASK PRACTICA_FINAL_DAW.WAREHOUSE.TASK_ACTUALIZAR_FACT_VENTAS RESUME;