USE DATABASE PRACTICA_FINAL_DAW;

-- ==========================================
-- 1. REFRESCAMOS LA TABLA DE HECHOS HISTÓRICA
-- ==========================================
CREATE OR REPLACE TABLE PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS AS
SELECT 
    base.ID_PEDIDO, base.ID_LINEA, base.ID_ARTICULO, base.ID_TIENDA, 
    base.ID_CLIENTE, base.ID_PROMOCION, base.TIPO_OPERACION, base.UNIDADES, 
    base.IMPORTE_USD,
    ROUND(base.IMPORTE_USD * dt.TIPO_CAMBIO_TIENDA, 2) AS IMPORTE_MONEDA_TIENDA,
    ROUND(base.IMPORTE_USD * dc.TIPO_CAMBIO_CLIENTE, 2) AS IMPORTE_MONEDA_CLIENTE,
    base.FECHA_HORA_PEDIDO_UTC,
    CONVERT_TIMEZONE('UTC', dt.ZONA_HORARIA_TIENDA, base.FECHA_HORA_PEDIDO_UTC) AS FECHA_HORA_LOCAL_TIENDA,
    CONVERT_TIMEZONE('UTC', dc.ZONA_HORARIA_CLIENTE, base.FECHA_HORA_PEDIDO_UTC) AS FECHA_HORA_LOCAL_CLIENTE,
    
    -- >>> NUEVA LÓGICA DE NEGOCIO <<<
    CASE 
        WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 0 THEN 1 -- En plazo
        WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 10 THEN 2 -- Entrega tardía
        WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 30 THEN 3 -- Entrega crítica
        ELSE 0 -- Fuera de plazo (> 30 días)
    END AS ID_PLAZO_ENTREGA
    
FROM (
    SELECT 
        l.L_ORDERKEY AS ID_PEDIDO, l.L_LINENUMBER AS ID_LINEA, l.L_PARTKEY AS ID_ARTICULO,
        o.O_STOREKEY AS ID_TIENDA, o.O_CUSTKEY AS ID_CLIENTE, prom.ID_PROMOCION,
        CASE WHEN l.L_RETURNFLAG = 'R' THEN 'Devolución' ELSE 'Venta' END AS TIPO_OPERACION,
        l.L_QUANTITY AS UNIDADES, l.L_EXTENDEDPRICE AS IMPORTE_USD,
        o.O_ORDERDATETIME AS FECHA_HORA_PEDIDO_UTC, l.L_COMMITDATE AS FECHA_ESTIMADA, l.L_RECEIPTDATE AS FECHA_ENTREGA
    FROM PRACTICA_FINAL_DAW.STAGING.STG_LINEITEM l
    INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_ORDERS o ON l.L_ORDERKEY = o.O_ORDERKEY
    INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_TIENDA t ON o.O_STOREKEY = t.ID_TIENDA
    LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_PROMOCION prom 
        ON o.O_ORDERDATE >= prom.FECHA_INICIO 
        AND o.O_ORDERDATE <= prom.FECHA_FIN
        AND (prom.N_NATIONKEY IS NULL OR prom.N_NATIONKEY = t.N_NATIONKEY)
) AS base
LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_TIENDA dt ON base.ID_TIENDA = dt.ID_TIENDA
LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON base.ID_CLIENTE = dc.ID_CLIENTE;


-- ==========================================
-- 2. ACTUALIZAMOS LA VISTA EN ANALYTICS
-- ==========================================
CREATE OR REPLACE SECURE VIEW PRACTICA_FINAL_DAW.ANALYTICS.V_CALIDAD_ENTREGAS AS
SELECT 
    dc.REGION_CLIENTE,
    -- Añadimos la nueva etiqueta de texto
    CASE 
        WHEN fv.ID_PLAZO_ENTREGA = 1 THEN 'En Plazo'
        WHEN fv.ID_PLAZO_ENTREGA = 2 THEN 'Entrega Tardía'
        WHEN fv.ID_PLAZO_ENTREGA = 3 THEN 'Entrega Crítica'
        WHEN fv.ID_PLAZO_ENTREGA = 0 THEN 'Fuera de Plazo'
    END AS ESTADO_ENTREGA,
    COUNT(fv.ID_PEDIDO) AS VOLUMEN_PEDIDOS
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON fv.ID_CLIENTE = dc.ID_CLIENTE
GROUP BY dc.REGION_CLIENTE, fv.ID_PLAZO_ENTREGA;


-- ==========================================
-- 3. ACTUALIZAMOS LA TASK PARA DATOS FUTUROS
-- ==========================================
-- (Nota: Para reemplazar una Task, primero hay que suspenderla)
ALTER TASK IF EXISTS PRACTICA_FINAL_DAW.WAREHOUSE.TASK_ACTUALIZAR_FACT_VENTAS SUSPEND;

CREATE OR REPLACE TASK PRACTICA_FINAL_DAW.WAREHOUSE.TASK_ACTUALIZAR_FACT_VENTAS
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('PRACTICA_FINAL_DAW.RAW.STREAM_NUEVAS_VENTAS')
AS
  INSERT INTO PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS
  SELECT 
      base.ID_PEDIDO, base.ID_LINEA, base.ID_ARTICULO, base.ID_TIENDA, 
      base.ID_CLIENTE, base.ID_PROMOCION, base.TIPO_OPERACION, base.UNIDADES, base.IMPORTE_USD,
      ROUND(base.IMPORTE_USD * dt.TIPO_CAMBIO_TIENDA, 2), ROUND(base.IMPORTE_USD * dc.TIPO_CAMBIO_CLIENTE, 2),
      base.FECHA_HORA_PEDIDO_UTC, CONVERT_TIMEZONE('UTC', dt.ZONA_HORARIA_TIENDA, base.FECHA_HORA_PEDIDO_UTC), CONVERT_TIMEZONE('UTC', dc.ZONA_HORARIA_CLIENTE, base.FECHA_HORA_PEDIDO_UTC),
      -- Nueva lógica en la inserción incremental
      CASE 
          WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 0 THEN 1
          WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 10 THEN 2
          WHEN DATEDIFF(day, base.FECHA_ESTIMADA, base.FECHA_ENTREGA) <= 30 THEN 3
          ELSE 0
      END
  FROM (
      SELECT 
          s.L_ORDERKEY AS ID_PEDIDO, s.L_LINENUMBER AS ID_LINEA, s.L_PARTKEY AS ID_ARTICULO,
          o.O_STOREKEY AS ID_TIENDA, o.O_CUSTKEY AS ID_CLIENTE, prom.ID_PROMOCION,
          CASE WHEN s.L_RETURNFLAG = 'R' THEN 'Devolución' ELSE 'Venta' END AS TIPO_OPERACION,
          s.L_QUANTITY AS UNIDADES, s.L_EXTENDEDPRICE AS IMPORTE_USD,
          o.O_ORDERDATETIME AS FECHA_HORA_PEDIDO_UTC, s.L_COMMITDATE AS FECHA_ESTIMADA, s.L_RECEIPTDATE AS FECHA_ENTREGA
      FROM PRACTICA_FINAL_DAW.RAW.STREAM_NUEVAS_VENTAS s
      INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_ORDERS o ON s.L_ORDERKEY = o.O_ORDERKEY
      INNER JOIN PRACTICA_FINAL_DAW.STAGING.STG_TIENDA t ON o.O_STOREKEY = t.ID_TIENDA
      LEFT JOIN PRACTICA_FINAL_DAW.STAGING.STG_PROMOCION prom 
          ON o.O_ORDERDATE >= prom.FECHA_INICIO AND o.O_ORDERDATE <= prom.FECHA_FIN AND (prom.N_NATIONKEY IS NULL OR prom.N_NATIONKEY = t.N_NATIONKEY)
      WHERE s.METADATA$ACTION = 'INSERT' AND s.METADATA$ISUPDATE = FALSE
  ) AS base
  LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_TIENDA dt ON base.ID_TIENDA = dt.ID_TIENDA
  LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON base.ID_CLIENTE = dc.ID_CLIENTE;

-- Volvemos a encender la task
ALTER TASK PRACTICA_FINAL_DAW.WAREHOUSE.TASK_ACTUALIZAR_FACT_VENTAS RESUME;