-- 1. Creamos el esquema ANALYTICS
CREATE SCHEMA IF NOT EXISTS PRACTICA_FINAL_DAW.ANALYTICS;
USE SCHEMA PRACTICA_FINAL_DAW.ANALYTICS;

-- 2. Implementación de Seguridad (Requisito Parte E)
-- Creamos un rol para el usuario de negocio y le damos acceso SOLO a este esquema
CREATE ROLE IF NOT EXISTS ROL_ANALISTA;
GRANT USAGE ON DATABASE PRACTICA_FINAL_DAW TO ROLE ROL_ANALISTA;
GRANT USAGE ON SCHEMA PRACTICA_FINAL_DAW.ANALYTICS TO ROLE ROL_ANALISTA;
-- Le damos permiso para leer todas las vistas futuras de este esquema
GRANT SELECT ON ALL VIEWS IN SCHEMA PRACTICA_FINAL_DAW.ANALYTICS TO ROLE ROL_ANALISTA;

-- 3. CREACIÓN DE LAS 5 CONSULTAS DE NEGOCIO (Usamos SECURE VIEW por seguridad)

-- Consulta 1: Rendimiento por Tienda (Agregada a tienda con su moneda local)
CREATE OR REPLACE SECURE VIEW V_ANALISIS_TIENDA AS
SELECT 
    dt.PAIS_TIENDA,
    dt.MONEDA_TIENDA,
    fv.TIPO_OPERACION,
    COUNT(fv.ID_PEDIDO) AS TOTAL_OPERACIONES,
    SUM(fv.UNIDADES) AS TOTAL_UNIDADES,
    SUM(fv.IMPORTE_MONEDA_TIENDA) AS TOTAL_IMPORTE_LOCAL
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_TIENDA dt ON fv.ID_TIENDA = dt.ID_TIENDA
GROUP BY dt.PAIS_TIENDA, dt.MONEDA_TIENDA, fv.TIPO_OPERACION;

-- Consulta 2: Gasto por Cliente y Región (Agregada a cliente con su moneda local)
CREATE OR REPLACE SECURE VIEW V_ANALISIS_CLIENTE AS
SELECT 
    dc.REGION_CLIENTE,
    dc.PAIS_CLIENTE,
    dc.MONEDA_CLIENTE,
    COUNT(DISTINCT fv.ID_CLIENTE) AS NUMERO_CLIENTES_ACTIVOS,
    SUM(fv.IMPORTE_MONEDA_CLIENTE) AS INGRESOS_TOTALES_LOCAL
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON fv.ID_CLIENTE = dc.ID_CLIENTE
WHERE fv.TIPO_OPERACION = 'Venta'
GROUP BY dc.REGION_CLIENTE, dc.PAIS_CLIENTE, dc.MONEDA_CLIENTE;

-- Consulta 3: Calidad del Servicio (Plazos de entrega)
CREATE OR REPLACE SECURE VIEW V_CALIDAD_ENTREGAS AS
SELECT 
    dc.REGION_CLIENTE,
    CASE 
        WHEN fv.ID_PLAZO_ENTREGA = 1 THEN 'En Plazo'
        WHEN fv.ID_PLAZO_ENTREGA = 2 THEN 'Entrega Tardía'
        WHEN fv.ID_PLAZO_ENTREGA = 0 THEN 'Fuera de Plazo'
    END AS ESTADO_ENTREGA,
    COUNT(fv.ID_PEDIDO) AS VOLUMEN_PEDIDOS
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON fv.ID_CLIENTE = dc.ID_CLIENTE
GROUP BY dc.REGION_CLIENTE, fv.ID_PLAZO_ENTREGA;

-- Consulta 4: Impacto de Promociones en Ventas
CREATE OR REPLACE SECURE VIEW V_IMPACTO_PROMOCIONES AS
SELECT 
    COALESCE(dp.NOMBRE_PROMO, 'Sin Promoción (Venta Regular)') AS CAMPANA,
    COUNT(fv.ID_PEDIDO) AS NUM_VENTAS,
    SUM(fv.IMPORTE_USD) AS INGRESOS_USD
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
LEFT JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_PROMOCION dp ON fv.ID_PROMOCION = dp.ID_PROMOCION
WHERE fv.TIPO_OPERACION = 'Venta'
GROUP BY dp.NOMBRE_PROMO;

-- Consulta 5: Tendencia Temporal (Usando la zona horaria del cliente)
CREATE OR REPLACE SECURE VIEW V_TENDENCIA_TEMPORAL AS
SELECT 
    DATE_TRUNC('MONTH', fv.FECHA_HORA_LOCAL_CLIENTE) AS MES_VENTA,
    dc.REGION_CLIENTE,
    SUM(fv.IMPORTE_USD) AS INGRESOS_USD
FROM PRACTICA_FINAL_DAW.WAREHOUSE.FACT_VENTAS fv
JOIN PRACTICA_FINAL_DAW.WAREHOUSE.DIM_CLIENTE dc ON fv.ID_CLIENTE = dc.ID_CLIENTE
WHERE fv.TIPO_OPERACION = 'Venta'
GROUP BY DATE_TRUNC('MONTH', fv.FECHA_HORA_LOCAL_CLIENTE), dc.REGION_CLIENTE
ORDER BY MES_VENTA DESC;