USE DATABASE PRACTICA_FINAL_DAW;

-- 1. Creamos el esquema STAGING
CREATE SCHEMA IF NOT EXISTS STAGING;
USE SCHEMA STAGING;

-- 2. Creamos las vistas de limpieza

-- STG_ORDERS: Aquí aplicamos la limpieza del campo O_CLERK
CREATE OR REPLACE VIEW STG_ORDERS AS
SELECT 
    O_ORDERKEY,
    O_CUSTKEY,
    O_ORDERSTATUS,
    O_TOTALPRICE,
    O_ORDERDATE,
    O_ORDERPRIORITY,
    -- Limpieza: Reemplazamos 'Clerk#' por nada y lo convertimos a NUMBER
    CAST(REPLACE(O_CLERK, 'Clerk#', '') AS NUMBER) AS O_CLERK_ID,
    O_SHIPPRIORITY,
    O_COMMENT,
    O_ORDERDATETIME,
    O_STOREKEY
FROM PRACTICA_FINAL_DAW.RAW.RAW_ORDERS;

-- STG_LINEITEM: La dejamos lista para la tabla de hechos
CREATE OR REPLACE VIEW STG_LINEITEM AS
SELECT 
    L_ORDERKEY,
    L_PARTKEY,
    L_SUPPKEY,
    L_LINENUMBER,
    L_QUANTITY,
    L_EXTENDEDPRICE,
    L_DISCOUNT,
    L_TAX,
    L_RETURNFLAG, -- Crucial para saber si es venta o devolución
    L_LINESTATUS,
    L_SHIPDATE,
    L_COMMITDATE, -- Fecha estimada (la usaremos para el plazo de entrega)
    L_RECEIPTDATE, -- Fecha real de entrega
    L_SHIPINSTRUCT,
    L_SHIPMODE,
    L_COMMENT
FROM PRACTICA_FINAL_DAW.RAW.RAW_LINEITEM;

-- STG_NATION: País con su zona horaria
CREATE OR REPLACE VIEW STG_NATION AS
SELECT 
    N_NATIONKEY,
    N_NAME,
    N_REGIONKEY,
    N_COMMENT,
    N_TIMEZONE
FROM PRACTICA_FINAL_DAW.RAW.RAW_NATION;

-- Vistas directas (pass-through) para el resto de dimensiones
CREATE OR REPLACE VIEW STG_REGION AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_REGION;
CREATE OR REPLACE VIEW STG_CUSTOMER AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_CUSTOMER;
CREATE OR REPLACE VIEW STG_PART AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_PART;
CREATE OR REPLACE VIEW STG_TIENDA AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_TENDA;
CREATE OR REPLACE VIEW STG_PROMOCION AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_PROMOCION;
CREATE OR REPLACE VIEW STG_CAMBIO AS SELECT * FROM PRACTICA_FINAL_DAW.RAW.RAW_CAMBIO;